name: pytorch-gpu
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pytorch-lightning
  - opencv
  - jupyterlab-nvdashboard
  - mlflow
  - pip:
    - ollama
    - chromadb
