name: pytorch-gpu
channels:
  - conda-forge
dependencies:
  - python=3.13
  - ipykernel
  - pip
  - pytorch-lightning
  - opencv
  - jupyterlab-nvdashboard
  - mlflow
  - chromadb
  - pip:
      - --index-url https://download.pytorch.org/whl/cu130
      - torch
      - torchvision
      - torchaudio
